'use strict';
const STATIC_BASE="/GG1102/";
function routePath(){const p=location.pathname;const v=p.startsWith(STATIC_BASE)?"/"+p.slice(STATIC_BASE.length):p;return v==="/"?v:v.replace(/\/$/,"");}

const $=s=>document.querySelector(s);
const el=(tag,content,cls)=>{const n=document.createElement(tag);if(content!==undefined)n.textContent=content;if(cls)n.className=cls;return n;};
const labels={all:'Todo',solar:'Cuidado de día',hidratacion:'Hidratación',rutina:'Tu rutina'};
let catalog=[],category='all',query='',saved=[],toastTimer;
try{const value=JSON.parse(localStorage.getItem('tgmx.selection.v1')||'[]');if(Array.isArray(value))saved=value.filter(s=>typeof s==='string').slice(0,100);}catch{}
function notify(text){$('#shop-message').textContent=text;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('#shop-message').textContent='';},3200);}
function save(id){const focusId=document.activeElement?.getAttribute('data-save-id');if(saved.includes(id)){saved=saved.filter(x=>x!==id);notify('Quitado de tu selección.');}else{saved.push(id);notify('Guardado en tu selección.');}try{localStorage.setItem('tgmx.selection.v1',JSON.stringify(saved));}catch{notify('Tu navegador no permite guardar la lista. Se conservará mientras tengas esta página abierta.');}updateCount();renderCurrent();if(focusId)document.querySelector(`[data-save-id="${CSS.escape(focusId)}"]`)?.focus({preventScroll:true});}
function updateCount(){$('#saved-count').textContent=saved.filter(id=>catalog.some(p=>p.id===id)).length;}
function image(p){const img=el('img');img.src=p.image_path||`${STATIC_BASE}assets/${p.visual}.svg`;img.alt=p.image_path?`${p.name}: imagen proporcionada para la ficha`:'Ilustración de un envase genérico; no es fotografía del producto';img.loading='lazy';img.width=400;img.height=500;return img;}
function saveButton(p,detail=false){const b=el('button',detail?(saved.includes(p.id)?'Guardado ✓':'Guardar en mi selección'):(saved.includes(p.id)?'♥':'♡'),detail?'button outline':'save-button');b.type='button';b.dataset.saveId=p.id;b.classList.toggle('saved',saved.includes(p.id));b.setAttribute('aria-label',`${saved.includes(p.id)?'Quitar':'Guardar'} ${p.name}`);b.setAttribute('aria-pressed',String(saved.includes(p.id)));b.onclick=()=>save(p.id);return b;}
function buyingLink(p){const a=el('a','Ver en YesStyle ›','button primary');const tracking=new URLSearchParams();const params=new URLSearchParams(location.search);for(const key of ['video','campaign'])if(params.get(key))tracking.set(key,params.get(key).slice(0,80));a.href=p.buy_url;a.target='_blank';a.rel='sponsored nofollow noopener noreferrer';return a;}
function internal(path){const url=new URL(path,location.origin);if(!url.pathname.startsWith(STATIC_BASE))url.pathname=STATIC_BASE+url.pathname.replace(/^\/+/,"");const params=new URLSearchParams(location.search);for(const k of ['video','campaign'])if(params.get(k))url.searchParams.set(k,params.get(k).slice(0,80));return url.pathname+url.search+url.hash;}
function card(p){const item=el('article',undefined,'product-card');const photo=el('div',undefined,'product-photo');const a=el('a');a.href=internal('/shop/product/'+p.id);a.setAttribute('aria-label','Ver '+p.name);a.append(image(p));photo.append(a,el('span',p.ready?'Enlace verificado':'En revisión','product-status'),saveButton(p));if(!p.image_path)photo.append(el('span','ILUSTRACIÓN PROVISIONAL','image-note'));const copy=el('div',undefined,'product-copy');const title=el('h3');const titleLink=el('a',p.name);titleLink.href=a.href;title.append(titleLink);copy.append(el('div',p.brand,'brand'),title,el('p',p.subtitle));const meta=el('div',undefined,'product-meta');const price=p.price_mxn!==null?new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(p.price_mxn)+' MXN':'Precio por confirmar';const detail=el('a','Ver detalles ›');detail.href=a.href;meta.append(el('span',price),detail);copy.append(meta);item.append(photo,copy);return item;}
function grid(target,products,empty){target.replaceChildren();for(const p of products)target.append(card(p));if(!products.length)target.append(el('p',empty,'empty'));}
function renderCollection(){grid($('#shop-products'),catalog.filter(p=>(category==='all'||p.category===category)&&`${p.name} ${p.brand} ${p.concern}`.toLocaleLowerCase('es-MX').includes(query.toLocaleLowerCase('es-MX'))),'No encontramos opciones con esa búsqueda. Prueba otra categoría o palabra.');const filters=$('#shop-filters');filters.replaceChildren();for(const [key,label] of Object.entries(labels)){const b=el('button',label,key===category?'active':'');b.type='button';b.setAttribute('aria-pressed',String(key===category));b.onclick=()=>{category=key;renderCollection();};filters.append(b);}}
function renderDetail(slug){const p=catalog.find(x=>x.id===slug);if(!p){$('#product-view').hidden=true;$('#error-view').hidden=false;document.title='Página no disponible · Tokyo Glow MX';return;}const root=$('#product-view');root.replaceChildren();const crumb=el('div',undefined,'breadcrumb');const back=el('a','La selección');back.href=internal('/#collection');crumb.append(back,document.createTextNode(' / '+p.name));root.append(crumb);const layout=el('div',undefined,'detail-grid');const photo=el('div',undefined,'detail-image');const img=image(p);img.loading='eager';photo.append(img);if(!p.image_path)photo.append(el('span','ILUSTRACIÓN · ENVASE NO CONFIRMADO','image-note'));const copy=el('div',undefined,'detail-copy');copy.append(el('p',p.brand.toUpperCase()+' / '+p.concern.toUpperCase(),'eyebrow'),el('h1',p.name),el('p',p.description));
if(p.ready){if(p.variant)copy.append(el('p',p.variant));if(p.price_mxn!==null){copy.append(el('p',new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(p.price_mxn)+' MXN','price'),el('p',`Precio de referencia revisado el ${p.verified_on}. Confirma el precio actual en YesStyle.`));}const actions=el('div',undefined,'detail-actions');actions.append(buyingLink(p),saveButton(p,true));copy.append(actions,el('p','Publicidad · Enlace de afiliado. Podemos recibir una comisión. Compra, pago y envío se realizan con YesStyle.'));}else{const note=el('div',undefined,'pending');note.append(el('strong','Estamos revisando esta opción.'),el('p','La versión exacta, el precio, el envío a México y el enlace de compra aún no están confirmados. Puedes guardarla para volver después.'));copy.append(note);const actions=el('div',undefined,'detail-actions');actions.append(saveButton(p,true));copy.append(actions);}
for(const [title,text] of [['Cómo incorporarlo',p.usage],['Antes de comprar','En YesStyle revisa la presentación exacta, precio, stock, envío a tu código postal, posibles cargos y condiciones de devolución. Tokyo Glow MX no procesa pagos ni prepara pedidos.'],['Cuida tu piel',p.caution||'Sigue las instrucciones del fabricante. Introduce productos nuevos de uno en uno. Si tienes irritación persistente, consulta a un profesional.']]){const detail=el('details');detail.append(el('summary',title),el('p',text));copy.append(detail);}layout.append(photo,copy);root.append(layout);const related=el('div',undefined,'related');related.append(el('h2','Sigue explorando'));const cards=el('div',undefined,'product-grid');grid(cards,catalog.filter(x=>x.id!==p.id).slice(0,3),'');related.append(cards);root.append(related);document.title=p.name+' · Tokyo Glow MX';}
function renderCurrent(){const path=routePath();$('#home-view').hidden=path!=='/'&&path!=='/shop';$('#saved-view').hidden=path!=='/shop/saved';$('#product-view').hidden=!path.startsWith('/shop/product/');$('#error-view').hidden=true;if(!$('#home-view').hidden)renderCollection();else if(!$('#saved-view').hidden){grid($('#saved-products'),catalog.filter(p=>saved.includes(p.id)),'Tu selección está vacía. Explora la colección y toca el corazón para guardar lo que te interese.');document.title='Mi selección · Tokyo Glow MX';}else if(!$('#product-view').hidden)renderDetail(path.split('/').pop());else $('#error-view').hidden=false;}
function info(title,body){$('#dialog-title').textContent=title;$('#dialog-body').textContent=body;$('#info-dialog').showModal();}
$('#shipping-info').onclick=()=>info('Envío y devoluciones','La compra se realiza en YesStyle. Antes de pagar, confirma allí disponibilidad, tiempos y costo de envío a México, posibles cargos de importación y condiciones de devolución. Tokyo Glow MX no vende, cobra ni envía estos productos. No hemos confirmado condiciones de envío para los productos que aparecen en revisión.');
$('#privacy-info').onclick=()=>info('Tu privacidad y nuestros enlaces','Tu selección se guarda únicamente en este navegador mediante almacenamiento local. No pedimos cuentas ni datos de pago. Esta versión no registra clics de compra en Tokyo Glow MX. El proveedor de alojamiento y YesStyle pueden procesar datos según sus propias políticas. Podemos recibir una comisión por compras desde nuestros enlaces de afiliado. YesStyle tiene sus propias condiciones y políticas.');
$('#close-dialog').onclick=()=>$('#info-dialog').close();$('#shop-search').oninput=e=>{query=e.target.value;renderCollection();};$('#year').textContent=new Intl.DateTimeFormat('en',{timeZone:'America/Monterrey',year:'numeric'}).format(new Date());document.querySelectorAll('a[href^="/"]').forEach(a=>a.href=internal(a.getAttribute('href')));
(async()=>{try{const r=await fetch(STATIC_BASE+'api/shop.json');if(!r.ok)throw Error();const state=await r.json();catalog=state.products;updateCount();renderCurrent();if(state.brand.tiktok_url)$('#tiktok-link').href=state.brand.tiktok_url;}catch{grid($('#shop-products'),[],'No pudimos cargar la selección. Intenta de nuevo en un momento.');if(routePath().startsWith('/shop/product/')){const message=el('p','No pudimos cargar este producto. Vuelve a intentarlo.','empty');$('#product-view').append(message);$('#home-view').hidden=true;$('#product-view').hidden=false;}notify('La selección no está disponible en este momento.');}})();
